name: Build & Test
on:
  push:
    branches: [main]

jobs:
  build-debug:
      name: Build Lib/Tests Debug
      strategy:
        matrix:
          os:
            - ubuntu-24.04
            - windows-2022
            - macos-15

      runs-on: ${{ matrix.os }}
      steps:
        - name: 'Checkout ${{ github.repositoryUrl }} ${{ github.base_ref }}'
          uses: actions/checkout@v2
          
        - name: Build Library Debug
          uses: actions-rs/cargo@v1
          with:
            command: test
            args: "--test '*'"
